
x-env-db: &env_db
  DB_HOST: db
  DB_PORT: "3306"
  DB_USER: app
  DB_PASSWORD: app

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./codigo/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-uapp","-papp"]
      interval: 5s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 6

  auth-api:
    build: ./codigo/auth-api
    environment:
      <<: *env_db
      DB_NAME: usuarios_db
      SERVICE_NAME: auth-api
      JWT_SECRET: "supersecret_dev_only"
      JWT_EXPIRES: "12h"
      REDIS_URL: "redis://redis:6379"
    depends_on: { db: { condition: service_healthy } }
    expose: ["3000"]

  usuarios-api:
    build: ./codigo/usuarios-api
    environment:
      <<: *env_db
      DB_NAME: usuarios_db
      SERVICE_NAME: usuarios-api
      REDIS_URL: "redis://redis:6379"
    depends_on: { db: { condition: service_healthy } }
    expose: ["3000"]
    ports:
      - "3001:3000"

  proyectos-api:
    build: ./codigo/proyectos-api
    environment:
      <<: *env_db
      DB_NAME: proyectos_db
      SERVICE_NAME: proyectos-api
      JWT_SECRET: "supersecret_dev_only"
      REDIS_URL: "redis://redis:6379"
    depends_on: { db: { condition: service_healthy } }
    expose: ["3000"]

  tareas-api:
    build: ./codigo/tareas-api
    environment:
      <<: *env_db
      DB_NAME: proyectos_db
      SERVICE_NAME: tareas-api
      JWT_SECRET: "supersecret_dev_only"
      REDIS_URL: "redis://redis:6379"
      USE_QUEUE: "1"
      START_TAREAS_WORKER: "1"
    depends_on: { db: { condition: service_healthy } }
    expose: ["3000"]

  gateway:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    volumes:
      - ./codigo/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-api
      - usuarios-api
      - proyectos-api
      - tareas-api

volumes:
  db_data:
